
filegroup(
  name = "libapril_tags_module.so_release", 
  srcs = ["libapril_tags_module.so"],
  visibility = ["//visibility:public"],
)
 
filegroup(
  name = "libfiducials_module.so_release", 
  srcs = ["libfiducials_module.so"],
  visibility = ["//visibility:public"],
)
 
filegroup(
  name = "libapril_tags3_module.so_release", 
  srcs = ["libapril_tags3_module.so"],
  visibility = ["//visibility:public"],
)
 